version: '3.8'

services:
  database:
      image: mysql:latest
      container_name: mysql
      ports:
        - 3310:3306
      environment:
        MYSQL_ROOT_PASSWORD: admin
      volumes:
        - .docker/mysql:/var/lib/mysql

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    volumes:
      - .docker/mongo:/data/db